### ISSUE TITLE
Is it really Supported in Android?

### ISSUE THREAD

**Issue by zywj** [fractaltech/react-native-timer#13]
there is no timeout effect in android

**Comment by chrisdukey** [comment]
Works perfectly in Android. Code [here](https://github.com/chrisdukey/TimerTest).

![ezgif-2-d1c814aa15](https://cloud.githubusercontent.com/assets/8040808/26456031/dadc56fa-4163-11e7-9716-2a4fbd4663b7.gif)

**Comment by zywj** [comment]
I used the same example code, but didn't get the same effect.   The word "hello!!!" was hided immediately .
react native:  0.44
react native timer: 1.3.1

**Comment by zywj** [comment]
I find the problem. Thanks

**Comment by jpamarohorta** [comment]
@zywj it's not working for me either. What the problem in your case?

**Comment by zywj** [comment]
@jpamarohorta Firstly, I found it was because one of my third party android projects. But after I upgraded RN version, the timer works successfully then. So, I am not sure what the problems is. You can try to upgrade RN version first.
