### ISSUE TITLE
Failure after Upgrading to React-Native 0.33

### ISSUE THREAD

**Issue by digitaldavenyc** [fractaltech/react-native-timer#2]
I just upgraded our project to the latest react-native version 0.33 and all my timers that use react-native-timer are executing immediately. This library was extremely useful for us because we did not just use it in React.Components but also in Redux.Actions to terminate fetch requests. 

I have tried updating to the latest version of this library but it does not seem to have many updates for a while. Any suggestions or is a update required for this to be compatible with the latest react-native version.

**Comment by digitaldavenyc** [comment]
It seems that this is related to an issue with react-native and debugging in Chrome ... [#4470](https://github.com/facebook/react-native/issues/4470)

**Comment by kapv89** [comment]
Hey @digitaldavenyc sorry for such a late reply, was busy with a lot of work. I noticed this behavior of `react-native-timer` in my own development work, but it is functioning properly in production builds. I am closing the issue. Please reopen the issue if you think I can help you with something about this.
