### ISSUE TITLE
clearInterval does not seem to be working.

### ISSUE THREAD

**Issue by vzelenko** [fractaltech/react-native-timer#4]
I have code that sets interval in a class using `timer.setInterval(this, 'name', cb.bind(this), 1000)` in 'render' method, which works perfectly, but when I try to clear the timer in callback 'cb' using `timer.clearInterval(this, 'name')`, it continues to fire the 'cb' anyways.

Am I doing something wrong?

**Comment by kapv89** [comment]
@vzelenko not sure, I have added a test for the same, you can go through it here: https://github.com/fractaltech/react-native-timer/blob/master/test/main.js#L88-L110

Everything seems to be working fine in this test.

**Comment by vzelenko** [comment]
OK, thanks for getting back to me on this.  Something must be weird on my side.  Sweet library, too, Kapil!

**Comment by kapv89** [comment]
Thanks @vzelenko !

**Comment by JulianKingman** [comment]
I had this issue, and had bound `timer` to `this` in the constructor, so just taking `this` out of the `clearInterval` worked (i.e. `timer.clearInterval('name')`)
