### ISSUE TITLE
timer.intervalExists is not defined

### ISSUE THREAD

**Issue by nhandyal** [fractaltech/react-native-timer#7]
It looks like intervalExists is defined in [src/index.js](https://github.com/fractaltech/react-native-timer/blob/master/src/index.js#L145), but isn't defined in lib/index.js

The other *.exists functions appear to be working fine.

```javascript
> timer.intervalExists
undefined
```

**Comment by kapv89** [comment]
Hey, thanks for this. There was a typo in `intervalExists` just fixed it. Try using version `1.3.1`

**Comment by nhandyal** [comment]
Awesome, that took care of it. Thanks for the quick response.
