### ISSUE TITLE
Undefined is not a function (evaluating 'func.apply(undefined,args)')

### ISSUE THREAD

**Issue by kapula6** [fractaltech/react-native-timer#8]
I am trying to use this timer but when I am running: 

`timer.setInterval(this, () => this.setState({ time: this.countTime()}), this.state.secondMs);`

I will get an error (title).
I am declaring timer with `const timer = require('react-native-timer');`

What I am doing wrong?

**Comment by kapv89** [comment]
Hey @kapula6 you have a syntax error. The syntax for creating an interval, as given in the docs, is:
`timer.setInterval(context, name, fn, interval);`

Whereas, what you are doing translates to:
`timer.setInterval(context, fn, interval);`

You are missing a `'name'` for the timer.

Try this:
`timer.setInterval(this, 'countTime', () => this.setState({time: this.countTime()}), this.state.secondMs);`

**Comment by kapula6** [comment]
Thanks, now it works.
