### ISSUE TITLE
Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by samkrut** [fractaltech/react-native-timer#9]
Whenever I hit the page with my interval timer I get the following error, "Cannot read property 'apply' of undefined".
Here is my code, 
  componentDidMount() {
    timer.setInterval(this, 'statusInterval', console.log('interval works'), 100);
  }
What am I doing wrong?

**Comment by kapv89** [comment]
The third argument should be a callback.

Try this:
`timer.setInterval(this, 'statusInterval', () => console.log('interval works'), 100);`

**Comment by samkrut** [comment]
Thanks this worked!
